name: money_note_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  drag_and_drop_lists: ^0.4.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.10.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.1

flutter:
  uses-material-design: true
